---
- name: "Download kibana rpm"
  get_url:
    url: "https://artifacts.elastic.co/downloads/kibana/kibana-{{ elk_stack_version }}-x86_64.rpm"
    dest: "/tmp/kibana-{{ elk_stack_version }}-x86_64.rpm"
  register: kibana_download
  until: kibana_download is succeeded
- name: "Install kibana"
  become: true
  yum:
    name: "/tmp/kibana-{{ elk_stack_version }}-x86_64.rpm"
    state: present
- name: "Configure kibana"
  become: true
  template:
    src: kibana.yaml.j2
    dest: "/etc/kibana/kibana.yml"
    mode: 0755
  notify: restart Kibana
